doc: link to a page by lang
lumeland/lume.land pull request #123
Opened 2024-05-03 12:29 UTC by geetsww

Hi 👋, 

I've been using the multilanguage today and found this way to link to a page in the current language:

```vto
{{ set about = search.page('about lang=' + lang) }}

<a href="{{ about.url }}">About</a> 
```

Thinks it would be nice to add in the doc.
*(+ a small information about the translated data only working at page level).*

Thank you!

2024-05-03 12:53 UTC, oscarotero commented
Thanks!

It's possible to use tags for this, but maybe it's more correct to use the `id` field, because it's used by multilanguage plugin to identify whether two pages have the same content in different languages.

So I'd recommend something like this:

```js
{{ set about = search.page('id=about lang=' + lang) }}
```

2024-05-04 11:01 UTC, geetsww commented
That's even better!

2024-05-04 11:14 UTC, oscarotero requested changes

2024-05-04 11:14 UTC, oscarotero commented on plugins/multilanguage.md
> +The easiest way to get the URL of a specific page in the current language is to use the [tags](../docs/creating-pages/tags.md) and [search.page()](../plugins/search.md#search-one-page) using a unique
This text should be changed to use `id` instead of `tags`.

2024-05-04 11:14 UTC, oscarotero commented on plugins/multilanguage.md
> +tags: ['about']
```suggestion
id: 'about'
```

2024-05-04 11:50 UTC, geetsww commented
Oh, sorry, I didn't pay much attention 😅

2024-05-04 17:23 UTC, oscarotero approved these changes

2024-05-04 17:24 UTC, merged

2024-05-04 17:24 UTC, oscarotero commented
Thank you!