Use lowercase, update @docsearch/css @docsearch/js to version: 3.8.2,…
lumeland/lume.land pull request #162
Opened 2024-12-23 14:08 UTC by cevdetardaharan

Changes in base.vto
- Use lowercase : (doctype and utf-8)[1]
- Update @docsearch/css and @docsearch/js to version: 3.8.2
- Optimize JS codes
- Split JS codes into two (theme code and docsearch)
- Re-order head [2]
Changes in themes.vto
- Delete closing `a` tag, because it's not needed and forgotten.

## Resources
- [1](https://endtimes.dev/why-lowercase-letters-save-data/)
- [2](https://rviscomi.github.io/capo.js/)

2024-12-23 14:18 UTC, cevdetardaharan commented
Removed it because it's really unnecessary and we should stop fixing fonts and let the browser choose the best: https://github.com/woocommerce/storefront/issues/698

2024-12-23 15:31 UTC, oscarotero requested changes

2024-12-23 15:31 UTC, oscarotero commented on _includes/styles/reset.css
> -  -moz-osx-font-smoothing: grayscale;
Please, don't remove this.
I know the old request to "don't fix font smoothing" but I think it's no longer valid.
Read this for more context: https://dbushell.com/2024/11/05/webkit-font-smoothing/

2025-01-06 16:09 UTC, oscarotero commented on _includes/styles/reset.css
> -  -moz-osx-font-smoothing: grayscale;
Ok no problem. I'm going to merge it and then revert this line.
Thanks!

2025-01-06 16:09 UTC, merged

2025-01-06 16:11 UTC, oscarotero commented on _includes/layouts/base.vto
> +    </script>
mm, this code no longer works. 
i'll revert this change too