New Showcase Item! (Lume Deno Blog)
lumeland/lume.land pull request #64
Opened 2023-04-18 18:27 UTC by ArnavK-09

2023-04-18 20:28 UTC, oscarotero requested changes

2023-04-18 20:28 UTC, oscarotero commented on showcase.yml
> +    description: eAnother Lume Template/ With CSS & Blog (MD) Support
I think there's a typo here:
```suggestion
    description: Another Lume Template/ With CSS & Blog (MD) Support
```

2023-04-19 00:44 UTC, ArnavK-09 commented
typo fix

2023-04-19 06:38 UTC, merged

2023-04-19 06:38 UTC, oscarotero commented
Thank you!!